Imports System.Drawing
Imports System.Windows.Forms
Imports Guna.UI2.WinForms
Imports System.ComponentModel

<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class AddMenuItemDialog
    ' FIXED: Now inherits from UserControl (matching the main file)
    Inherits System.Windows.Forms.UserControl

    ' Form Components
    Private components As System.ComponentModel.IContainer

    ' Clean up any resources being used.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    ' REQUIRED: Design-time component declarations and initialization.

    ' ===== UI COMPONENTS (WITH EVENTS) =====
    Friend WithEvents pnlMain As Guna2ShadowPanel
    Friend WithEvents lblTitle As Label
    Friend WithEvents lblItemName As Label
    Friend WithEvents txtItemName As Guna2TextBox
    Friend WithEvents lblItemPrice As Label
    Friend WithEvents txtItemPrice As Guna2TextBox
    Friend WithEvents lblCategory As Label
    Friend WithEvents cmbCategory As Guna2ComboBox
    Friend WithEvents lblImage As Label
    Friend WithEvents pnlImagePreview As Guna2ShadowPanel
    Friend WithEvents pbImagePreview As Guna2PictureBox
    Friend WithEvents lblImagePlaceholder As Label
    Friend WithEvents btnUploadImage As Guna2Button
    Friend WithEvents btnSave As Guna2Button
    Friend WithEvents btnCancel As Guna2Button
    Friend WithEvents btnClose As Guna2CircleButton

    ' ===== VALIDATION LABELS (NO EVENTS) =====
    Friend lblNameError As Label
    Friend lblPriceError As Label
    Friend lblCategoryError As Label
    Friend lblImageError As Label


    ''' <summary>
    ''' Initialize all UI components (Generated by the Designer)
    ''' </summary>
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        ' Use centralized AppTheme module for palette
        Me.components = New System.ComponentModel.Container()
        Me.pnlMain = New Guna2ShadowPanel()
        Me.btnClose = New Guna2CircleButton()
        Me.lblTitle = New Label()
        Me.lblItemName = New Label()
        Me.txtItemName = New Guna2TextBox()
        Me.lblNameError = New Label()
        Me.lblItemPrice = New Label()
        Me.txtItemPrice = New Guna2TextBox()
        Me.lblPriceError = New Label()
        Me.lblCategory = New Label()
        Me.cmbCategory = New Guna2ComboBox()
        Me.lblCategoryError = New Label()
        Me.lblImage = New Label()
        Me.pnlImagePreview = New Guna2ShadowPanel()
        Me.pbImagePreview = New Guna2PictureBox()
        Me.lblImagePlaceholder = New Label()
        Me.lblImageError = New Label()
        Me.btnUploadImage = New Guna2Button()
        Me.btnSave = New Guna2Button()
        Me.btnCancel = New Guna2Button()
        Me.pnlMain.SuspendLayout()
        Me.pnlImagePreview.SuspendLayout()
        CType(Me.pbImagePreview, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()

        ' UserControl properties (converted from Form properties)
        Me.AutoScaleMode = AutoScaleMode.None
        Me.Size = New Size(550, 680)
        Me.BackColor = Color.FromArgb(240, 240, 245)
        Me.Name = "AddMenuItemDialog"

        ' Main panel (card container)
        Me.pnlMain.Size = New Size(520, 650)
        Me.pnlMain.Location = New Point(15, 15)
        Me.pnlMain.BackColor = Color.Transparent
        Me.pnlMain.FillColor = Color.White
        Me.pnlMain.Radius = 20
        Me.pnlMain.ShadowColor = Color.Black
        Me.pnlMain.ShadowDepth = 30
        Me.pnlMain.ShadowShift = 5

        ' Close button (X)
        Me.btnClose.Size = New Size(35, 35)
        Me.btnClose.Location = New Point(470, 15)
        Me.btnClose.FillColor = Color.FromArgb(231, 76, 60)
        Me.btnClose.ForeColor = Color.White
        Me.btnClose.Font = New Font("Segoe UI", 12.0F, FontStyle.Bold)
        Me.btnClose.Text = "✕"
        Me.btnClose.Cursor = Cursors.Hand
        Me.btnClose.ShadowDecoration.Enabled = True
        Me.btnClose.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle

        ' Title label
        Me.lblTitle.Location = New Point(30, 25)
        Me.lblTitle.Size = New Size(400, 40)
        Me.lblTitle.Font = New Font("Segoe UI", 18.0F, FontStyle.Bold)
        Me.lblTitle.ForeColor = Color.FromArgb(33, 37, 41)
        Me.lblTitle.Text = "➕ Add New Menu Item"
        Me.lblTitle.AutoSize = False

        ' ===== ITEM NAME SECTION =====
        Me.lblItemName.Location = New Point(30, 90)
        Me.lblItemName.Size = New Size(150, 25)
        Me.lblItemName.Font = New Font("Segoe UI Semibold", 10.5F, FontStyle.Bold)
        Me.lblItemName.ForeColor = Color.FromArgb(33, 37, 41)
        Me.lblItemName.Text = "Item Name *"

        Me.txtItemName.Location = New Point(30, 120)
        Me.txtItemName.Size = New Size(460, 45)
        Me.txtItemName.BorderRadius = 12
        Me.txtItemName.BorderThickness = 2
        Me.txtItemName.BorderColor = Color.FromArgb(222, 226, 230)
        Me.txtItemName.Font = New Font("Segoe UI", 10.5F)
        Me.txtItemName.PlaceholderText = "e.g., Classic Burger"
        Me.txtItemName.PlaceholderForeColor = Color.FromArgb(134, 142, 150)
        Me.txtItemName.FocusedState.BorderColor = Color.FromArgb(52, 152, 219)
        Me.txtItemName.HoverState.BorderColor = Color.FromArgb(180, 180, 180)
        Me.txtItemName.MaxLength = 100

        Me.lblNameError.Location = New Point(35, 170)
        Me.lblNameError.Size = New Size(450, 20)
        Me.lblNameError.Font = New Font("Segoe UI", 8.5F, FontStyle.Regular)
        Me.lblNameError.ForeColor = Color.FromArgb(231, 76, 60)
        Me.lblNameError.Text = ""
        Me.lblNameError.Visible = False

        ' ===== PRICE SECTION =====
        Me.lblItemPrice.Location = New Point(30, 195)
        Me.lblItemPrice.Size = New Size(150, 25)
        Me.lblItemPrice.Font = New Font("Segoe UI Semibold", 10.5F, FontStyle.Bold)
        Me.lblItemPrice.ForeColor = Color.FromArgb(33, 37, 41)
        Me.lblItemPrice.Text = "Price (₱) *"

        Me.txtItemPrice.Location = New Point(30, 225)
        Me.txtItemPrice.Size = New Size(200, 45)
        Me.txtItemPrice.BorderRadius = 12
        Me.txtItemPrice.BorderThickness = 2
        Me.txtItemPrice.BorderColor = Color.FromArgb(222, 226, 230)
        Me.txtItemPrice.Font = New Font("Segoe UI", 10.5F)
        Me.txtItemPrice.PlaceholderText = "0.00"
        Me.txtItemPrice.PlaceholderForeColor = Color.FromArgb(134, 142, 150)
        Me.txtItemPrice.FocusedState.BorderColor = Color.FromArgb(52, 152, 219)
        Me.txtItemPrice.HoverState.BorderColor = Color.FromArgb(180, 180, 180)

        Me.lblPriceError.Location = New Point(35, 275)
        Me.lblPriceError.Size = New Size(190, 20)
        Me.lblPriceError.Font = New Font("Segoe UI", 8.5F, FontStyle.Regular)
        Me.lblPriceError.ForeColor = Color.FromArgb(231, 76, 60)
        Me.lblPriceError.Text = ""
        Me.lblPriceError.Visible = False

        ' ===== CATEGORY SECTION =====
        Me.lblCategory.Location = New Point(250, 195)
        Me.lblCategory.Size = New Size(150, 25)
        Me.lblCategory.Font = New Font("Segoe UI Semibold", 10.5F, FontStyle.Bold)
        Me.lblCategory.ForeColor = Color.FromArgb(33, 37, 41)
        Me.lblCategory.Text = "Category *"

        Me.cmbCategory.Location = New Point(250, 225)
        Me.cmbCategory.Size = New Size(240, 45)
        Me.cmbCategory.BorderRadius = 12
        Me.cmbCategory.BorderThickness = 2
        Me.cmbCategory.BorderColor = Color.FromArgb(222, 226, 230)
        Me.cmbCategory.Font = New Font("Segoe UI", 10.5F)
        Me.cmbCategory.ForeColor = Color.FromArgb(33, 37, 41)
        Me.cmbCategory.FocusedState.BorderColor = Color.FromArgb(52, 152, 219)
        Me.cmbCategory.HoverState.BorderColor = Color.FromArgb(180, 180, 180)
        Me.cmbCategory.DropDownStyle = ComboBoxStyle.DropDownList
        Me.cmbCategory.BackColor = Color.White
        Me.cmbCategory.FillColor = Color.White

        Me.lblCategoryError.Location = New Point(255, 275)
        Me.lblCategoryError.Size = New Size(230, 20)
        Me.lblCategoryError.Font = New Font("Segoe UI", 8.5F, FontStyle.Regular)
        Me.lblCategoryError.ForeColor = Color.FromArgb(231, 76, 60)
        Me.lblCategoryError.Text = ""
        Me.lblCategoryError.Visible = False

        ' ===== IMAGE SECTION =====
        Me.lblImage.Location = New Point(30, 305)
        Me.lblImage.Size = New Size(150, 25)
        Me.lblImage.Font = New Font("Segoe UI Semibold", 10.5F, FontStyle.Bold)
        Me.lblImage.ForeColor = Color.FromArgb(33, 37, 41)
        Me.lblImage.Text = "Item Image"

        ' Image preview panel
        Me.pnlImagePreview.Location = New Point(30, 335)
        Me.pnlImagePreview.Size = New Size(320, 220)
        Me.pnlImagePreview.BackColor = Color.Transparent
        Me.pnlImagePreview.FillColor = Color.FromArgb(250, 250, 252)
        Me.pnlImagePreview.Radius = 16
        Me.pnlImagePreview.ShadowColor = Color.Black
        Me.pnlImagePreview.ShadowDepth = 5
        Me.pnlImagePreview.ShadowShift = 2

        Me.pbImagePreview.Dock = DockStyle.Fill
        Me.pbImagePreview.SizeMode = PictureBoxSizeMode.Zoom
        Me.pbImagePreview.BackColor = Color.Transparent
        Me.pbImagePreview.FillColor = Color.Transparent

        Me.lblImagePlaceholder.Dock = DockStyle.Fill
        Me.lblImagePlaceholder.Font = New Font("Segoe UI", 14.0F, FontStyle.Bold)
        Me.lblImagePlaceholder.ForeColor = Color.FromArgb(134, 142, 150)
        Me.lblImagePlaceholder.Text = "📷" & vbCrLf & vbCrLf & "No image selected"
        Me.lblImagePlaceholder.TextAlign = ContentAlignment.MiddleCenter
        Me.lblImagePlaceholder.BackColor = Color.Transparent

        ' Add controls to image preview panel
        Me.pnlImagePreview.Controls.Add(Me.pbImagePreview)
        Me.pnlImagePreview.Controls.Add(Me.lblImagePlaceholder)

        Me.lblImageError.Location = New Point(35, 560)
        Me.lblImageError.Size = New Size(310, 20)
        Me.lblImageError.Font = New Font("Segoe UI", 8.5F, FontStyle.Regular)
        Me.lblImageError.ForeColor = Color.FromArgb(231, 76, 60)
        Me.lblImageError.Text = ""
        Me.lblImageError.Visible = False

        ' Upload image button
        Me.btnUploadImage.Location = New Point(365, 335)
        Me.btnUploadImage.Size = New Size(125, 50)
        Me.btnUploadImage.BorderRadius = 12
        Me.btnUploadImage.FillColor = Color.FromArgb(52, 152, 219)
        Me.btnUploadImage.Font = New Font("Segoe UI Semibold", 10.0F, FontStyle.Bold)
        Me.btnUploadImage.Text = "📷 Upload"
        Me.btnUploadImage.ForeColor = Color.White
        Me.btnUploadImage.Cursor = Cursors.Hand
        Me.btnUploadImage.ShadowDecoration.Enabled = True
        Me.btnUploadImage.ShadowDecoration.Depth = 8

        ' ===== ACTION BUTTONS =====
        Me.btnSave.Location = New Point(30, 590)
        Me.btnSave.Size = New Size(220, 50)
        Me.btnSave.BorderRadius = 14
        Me.btnSave.FillColor = Color.FromArgb(46, 204, 113)
        Me.btnSave.Font = New Font("Segoe UI Semibold", 11.0F, FontStyle.Bold)
        Me.btnSave.Text = "💾 Save Item"
        Me.btnSave.ForeColor = Color.White
        Me.btnSave.Cursor = Cursors.Hand
        Me.btnSave.ShadowDecoration.Enabled = True
        Me.btnSave.ShadowDecoration.Depth = 10
        Me.btnSave.Animated = True

        Me.btnCancel.Location = New Point(270, 590)
        Me.btnCancel.Size = New Size(220, 50)
        Me.btnCancel.BorderRadius = 14
        Me.btnCancel.FillColor = Color.FromArgb(149, 165, 166)
        Me.btnCancel.Font = New Font("Segoe UI Semibold", 11.0F, FontStyle.Bold)
        Me.btnCancel.Text = "✖ Cancel"
        Me.btnCancel.ForeColor = Color.White
        Me.btnCancel.Cursor = Cursors.Hand
        Me.btnCancel.ShadowDecoration.Enabled = True
        Me.btnCancel.ShadowDecoration.Depth = 10
        Me.btnCancel.Animated = True

        ' Add all controls to main panel
        Me.pnlMain.Controls.AddRange(New Control() {
            Me.btnClose, Me.lblTitle,
            Me.lblItemName, Me.txtItemName, Me.lblNameError,
            Me.lblItemPrice, Me.txtItemPrice, Me.lblPriceError,
            Me.lblCategory, Me.cmbCategory, Me.lblCategoryError,
            Me.lblImage, Me.pnlImagePreview, Me.lblImageError, Me.btnUploadImage,
            Me.btnSave, Me.btnCancel
        })

        ' Add main panel to UserControl
        Me.Controls.Add(Me.pnlMain)
        CType(Me.pbImagePreview, System.ComponentModel.ISupportInitialize).EndInit()
        Me.pnlImagePreview.ResumeLayout(False)
        Me.pnlMain.ResumeLayout(False)
        Me.ResumeLayout(False)

    End Sub

End Class