Imports System.Drawing
Imports System.Drawing.Drawing2D
Imports System.Windows.Forms
Imports Guna.UI2.WinForms

''' <summary>
''' Premium Modern Navigation Button UserControl
''' Enterprise-grade design with gradients and animations
''' </summary>
Partial Public Class ModernNavButton
    Inherits UserControl

    ' Public Event
    Public Event ButtonClicked(sender As Object, e As EventArgs)

    ' Private Fields (must be declared here since they are not AutoGenerated)
    Private _title As String = "Menu Item"
    Private _subtitle As String = "Description"
    Private _icon As String = "📊"
    Private _accentColor As Color = Color.FromArgb(251, 191, 36)
    Private _isActive As Boolean = False

    Public Sub New()
        ' This calls the designer-generated code to create and position controls
        InitializeComponent()

        ' Ensure control starts in the inactive (visible) state
        SetInactive()

        ' Add event handlers that reference private methods
        AddHandler btnMain.Click, AddressOf OnControlClicked
        AddHandler iconBadge.Click, AddressOf OnControlClicked
        AddHandler lblTitle.Click, AddressOf OnControlClicked
        AddHandler lblSubtitle.Click, AddressOf OnControlClicked
    End Sub

    Private Sub SetupControl()
        ' (kept for future initialization)
    End Sub

    ''' <summary>
    ''' Updates the button's content and accent color.
    ''' </summary>
    Public Sub SetContent(title As String, subtitle As String, icon As String, accentColor As Color)
        _title = title
        _subtitle = subtitle
        _icon = icon
        _accentColor = accentColor

        lblTitle.Text = title
        lblSubtitle.Text = subtitle
        iconBadge.Text = icon
        iconBadge.FillColor = accentColor
    End Sub

    ''' <summary>
    ''' Sets the button to the active state with enhanced styling.
    ''' </summary>
    Public Sub SetActive()
        _isActive = True

        ' Active state styling
        mainContainer.FillColor = Color.FromArgb(251, 191, 36)
        lblTitle.ForeColor = Color.FromArgb(20, 20, 20)
        lblSubtitle.ForeColor = Color.FromArgb(60, 60, 60)
        iconBadge.FillColor = Color.FromArgb(245, 158, 11)

        ' Use mainContainer border for glow instead of overlay panel to avoid hiding child controls
        mainContainer.BorderThickness = 3
        mainContainer.BorderColor = Color.FromArgb(251, 191, 36)

        ' Enhanced shadow
        mainContainer.ShadowDecoration.Depth = 20
        mainContainer.ShadowDecoration.Color = Color.FromArgb(100, 251, 191, 36)
    End Sub

    ''' <summary>
    ''' Sets the button to the inactive (default) state.
    ''' </summary>
    Public Sub SetInactive()
        _isActive = False

        ' Inactive state styling
        mainContainer.FillColor = Color.FromArgb(35, 40, 48)
        lblTitle.ForeColor = Color.FromArgb(220, 220, 220)
        lblSubtitle.ForeColor = Color.FromArgb(150, 155, 165)
        iconBadge.FillColor = _accentColor

        ' Remove glow overlay, use border reset
        mainContainer.BorderThickness = 0
        mainContainer.BorderColor = Color.Transparent

        ' Normal shadow
        mainContainer.ShadowDecoration.Depth = 10
        mainContainer.ShadowDecoration.Color = Color.FromArgb(60, 0, 0, 0)
    End Sub

    ''' <summary>
    ''' Central click handler for all clickable elements, raises the public event.
    ''' </summary>
    Private Sub OnControlClicked(sender As Object, e As EventArgs)
        RaiseEvent ButtonClicked(Me, EventArgs.Empty)
    End Sub

End Class